spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/userdb
    username: useradmin
    password: ${DB_PASSWORD:userpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

crypto:
  secret-key: ${SECRET_KEY:dominica@1232}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
