version: '3.8'

services:
  runzo-zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: runzo-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"

  runzo-kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: runzo-kafka
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: runzo-zookeeper:${ZOOKEEPER_PORT}

      # Listeners
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:${KAFKA_PORT},PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://runzo-kafka:${KAFKA_PORT},PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    depends_on:
      - runzo-zookeeper

  runzo-kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: runzo-kafka-ui
    ports:
      - "${KAFKA_UI_PORT}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: runzo-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: runzo-kafka:${KAFKA_PORT}
    depends_on:
      - runzo-kafka

  runzo-postgres-user:
    image: postgres:15
    container_name: runzo-postgres-user
    environment:
      POSTGRES_DB: ${USER_DB}
      POSTGRES_USER: ${USER_USER}
      POSTGRES_PASSWORD: ${USER_PASS}
    ports:
      - "${USER_PORT}:5432"
    volumes:
      - runzo_user_data:/var/lib/postgresql/data

  runzo-postgres-activity:
    image: postgres:15
    container_name: runzo-postgres-activity
    environment:
      POSTGRES_DB: ${ACTIVITY_DB}
      POSTGRES_USER: ${ACTIVITY_USER}
      POSTGRES_PASSWORD: ${ACTIVITY_PASS}
    ports:
      - "${ACTIVITY_PORT}:5432"
    volumes:
      - runzo_activity_data:/var/lib/postgresql/data

  runzo-postgres-alservice:
    image: postgres:15
    container_name: runzo-postgres-alservice
    environment:
      POSTGRES_DB: ${ALSERVICE_DB}
      POSTGRES_USER: ${ALSERVICE_USER}
      POSTGRES_PASSWORD: ${ALSERVICE_PASS}
    ports:
      - "${ALSERVICE_PORT}:5432"
    volumes:
      - runzo_alservice_data:/var/lib/postgresql/data

  runzo-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: runzo-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - runzo-postgres-user
      - runzo-postgres-activity
      - runzo-postgres-alservice

  runzo-redis:
    image: redis:7
    container_name: runzo-redis
    ports:
      - "${REDIS_PORT}:6379"

  runzo-redisinsight:
    image: redis/redisinsight:latest
    container_name: runzo-redisinsight
    ports:
      - "${REDIS_UI_PORT}:5540"
    volumes:
      - ./redisinsight_config.json:/data/redisinsight_config.json
    depends_on:
      - runzo-redis

volumes:
  runzo_user_data:
  runzo_activity_data:
  runzo_alservice_data:
